spring:
  application:
    name: LMS
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

security:
  jwt:
    issuer: ${ISSUER}
    secret-key: ${JWT_SECRET_KEY}